# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyTlolerRVEtl-yAHya5pmPCO_s87hjE
"""

# config.py
import os

# Base directory of repo
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Data directory (where Excel files are stored)
DATA_DIR = os.path.join(BASE_DIR, "data")